"Skills"
{
    "-5"
    {
        "ID" "-5"
        "name" "empty5"
        "type" "ultimate"
    }
	"-4"
    {
        "ID" "-4"
        "name" "empty4"
        "type" "active"
    }

    "-3"
    {
        "ID" "-3"
        "name" "empty3"
        "type" "active"
    }

    "-2"
    {
        "ID" "-2"
        "name" "empty2"
        "type" "active"
    }

    "-1"
    {
        "ID" "-1"
        "name" "empty1"
        "type" "active"
    }

    "0"
    {
        "ID" "0"
        "type" "active"
        "file_name" "cluster_shot"
        "max_lvl" "6"
        "lvl_gap" "5"
        "min_lvl" "2"
        "name" "cluster_shot"
        "unlocked" "true"
        "unlock_id"
            {
            "1" "1"
            "2" "2"
            }
    }

    "1"
    {
        "ID" "1"
        "type" "stats"
        "file_name" "agi_1"
        "stat_name" "agi"
        "agi"
        {
        "0" "0"
        "1" "2"
        "2" "4"
        "3" "8"
        "4" "12"
        "5" "20"
        "6" "30"
        "7" "40"
        "8" "60"
        "9" "80"
        "10" "100"
        "11" "150"
        "12" "200"
        "13" "250"
        "14" "300"
        "15" "400"
        "16" "500"
        "17" "600"
        "18" "700"
        "19" "850"
        "20" "1000"
        }
        "max_lvl" "20"
        "lvl_gap" "5"
        "min_lvl" "3"
        "unlocked" "false"
        "unlock_id"
            {
            "1" "3"
            "2" "4"
            }
    }

    "2"
    {
        "ID" "2"
        "type" "stats"
        "file_name" "move_speed_1"
        "stat_name" "movespeed"
        "movespeed"
        {
        "0" "0"
        "1" "10"
        "2" "25"
        "3" "30"
        "4" "45"
        "5" "60"
        "6" "75"
        "7" "80"
        "8" "100"
        }
        "max_lvl" "8"
        "lvl_gap" "8"
        "min_lvl" "3"
        "unlocked" "false"
        "unlock_id"
            {
            }
    }

    "3"
    {
        "ID" "3"
        "type" "passive"
        "file_name" "cancel_ranged_malus"
        "effect"
        {
        "1" "cancel_ranged_malus"
        }
        "max_lvl" "1"
        "lvl_gap" "1"
        "min_lvl" "10"
        "unlocked" "false"
        "unlock_id"
            {
            }
    }

    "4"
    {
        "ID" "4"
        "type" "stats"
        "file_name" "damage_1"
        "stat_name" "damage_mult"
        "damage_mult"
        {
        "0" "0"
        "1" "2"
        "2" "4"
        "3" "6"
        "4" "8"
        "5" "10"
        "6" "12"
        "7" "14"
        "8" "16"
        "9" "18"
        "10" "20"
        "11" "23"
        "12" "26"
        "13" "30"
        }
        "max_lvl" "13"
        "lvl_gap" "5"
        "min_lvl" "4"
        "unlocked" "false"
        "unlock_id"
            {
            "1" "5"
            }
    }
    "5"
    {
        "ID" "5"
        "type" "active"
        "file_name" "explosive_arrow"
        "max_lvl" "5"
        "lvl_gap" "8"
        "min_lvl" "5"
        "name" "explosive_arrow"
        "unlocked" "false"
        "unlock_id"
            {
              "1" "6"
              "2" "7"
              "3" "8"
            }
    }
    "6"
    {
        "ID" "6"
        "type" "active"
        "file_name" "arrows_rain"
        "max_lvl" "5"
        "lvl_gap" "8"
        "min_lvl" "8"
        "name" "arrows_rain"
        "unlocked" "false"
        "unlock_id"
            {
            }
    }
    "7"
    {
        "ID" "7"
        "type" "active"
        "file_name" "homming_arrow"
        "max_lvl" "6"
        "lvl_gap" "8"
        "min_lvl" "10"
        "name" "homming_arrow"
        "unlocked" "false"
        "unlock_id"
            {
              "1" "9"
            }
    }
    "8"
    {
        "ID" "8"
        "type" "active"
        "file_name" "focused_shot"
        "max_lvl" "7"
        "lvl_gap" "8"
        "min_lvl" "7"
        "name" "focused_shot"
        "unlocked" "false"
        "unlock_id"
            {
            }
    }
    "9"
    {
        "ID" "9"
        "type" "active"
        "file_name" "arrow_stream"
        "max_lvl" "7"
        "lvl_gap" "8"
        "min_lvl" "15"
        "name" "arrow_stream"
        "unlocked" "false"
        "unlock_id"
            {
            }
    }

}
