"shop_kv_file"
{
	
	"0"
	{
		"name"	"potion_row"
		"row"	
		{
			"0"	"item_red_potion"
			"1"	"item_blue_potion"
			"2"	"item_purple_potion"

		}
	}
	"1"
	{
		"name"	"weapon_row"
		"row"	
		{
			"0"	"item_rust_dagger"
			"1"	"item_rust_sword"
		}
	}
	"2"
	{
		"name"	"armor_row"
		"row"	
		{
			"0"	"item_leather_hood"
			"1"	"item_leather_vest"
			"2"	"item_leather_trousers"
			"3"	"item_leather_boots"
			"4"	"item_leather_gloves"
		}
	}






}